### ISSUE TITLE
raise NotImplementedError 

### ISSUE THREAD

**Issue by zxl1994** [aurora95/Keras-FCN#48]
I meet the error in epoch 1 with VOC2012

lr: 0.010000
Epoch 1/250
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 513, in get
    inputs = self.queue.get(block=True).get()
  File "D:\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "D:\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 379, in get_index
    return ds[i]
  File "D:\Python\Python36\lib\site-packages\keras\preprocessing\image.py", line 759, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "D:\Python\Python36\lib\site-packages\keras\preprocessing\image.py", line 805, in _get_batches_of_transformed_samples
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/demo/pycharmWorksapce/Keras-FCN-master/train.py", line 234, in <module>
    label_suffix=label_suffix, ignore_label=ignore_label, label_cval=label_cval)
  File "D:/demo/pycharmWorksapce/Keras-FCN-master/train.py", line 163, in train
    class_weight=class_weight
  File "D:\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\Python36\lib\site-packages\keras\engine\training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
  File "D:\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 518, in get
    raise StopIteration(e)
StopIteration

Process finished with exit code 1

**Comment by xiaofengqing** [comment]
I meet the same error . Have you already solved it?

**Comment by zxl1994** [comment]
@xiaofengqing not yet

**Comment by milumilule2** [comment]
@zxl1994 @xiaofengqing   Have you already solved this problem?  I have the same error.
during the steps:
**# Generate pretrained weights
python transfer_FCN.py

cd ~/src/Keras-FCN

# Run training
python train.py

# Evaluate the performance of the network
python evaluate.py**

I failed run python train.py ,  there is a value error"axes don't match array." Do you have this error?

**Comment by milumilule2** [comment]
@zxl1994 @xiaofengqing 
Have you already solved this problem? I have the same error with you.
during the steps:

1.# Generate pretrained weights
python transfer_FCN.py

2.# Run training
python train.py

3.# Evaluate the performance of the network
python evaluate.py


I failed run python train.py , there is a value error"axes don't match array." Do you have this error?

**Comment by milumilule2** [comment]
@zxl1994 @xiaofengqing 
Have you already solved this problem? I have the same error with you.
during the steps:

1.# Generate pretrained weights
python transfer_FCN.py

2.# Run training
python train.py

3.# Evaluate the performance of the network
python evaluate.py

I failed run python transfer_FCN.py , there is a value error"axes don't match array." Do you have this error?

**Comment by xiaofengqing** [comment]
When i Downgraded keras to 2.0.8，the problem is solved. @milumilule2 @zxl1994

**Comment by zwlshine** [comment]
@milumilule2  I run transfer_FCN.py successfully, I did not meet this error.

**Comment by milumilule2** [comment]
@xiaofengqing yes,  my keras version is 2.0.8, but it doesn't work. It still occurs the same issue.
 so what's your python and tensorflow version? my python version is 2.7, is it too old?

**Comment by xiaofengqing** [comment]
@milumilule2  TensorFlow 1.3 python3.4.3
