### ISSUE TITLE
error when run "python data_pascal_voc.py pascal_voc_setup"

### ISSUE THREAD

**Issue by xujoyce** [aurora95/Keras-FCN#69]
when I run "python data_pascal_voc.py pascal_voc_setup" to get the "combined_imageset_train.txt" file, error occurs as follows:

Traceback (most recent calls WITHOUT Sacred internals):
  File "data_pascal_voc.py", line 205, in pascal_voc_setup
    combined_annotations_path)
  File "data_pascal_voc.py", line 135, in pascal_voc_berkeley_combined
    mode=voc_data_subset_mode)
  File "/root/src/tf-image-segmentation/tf_image_segmentation/utils/pascal_voc.py", line 570, in get_augmented_pascal_image_annotation_filename_pairs
    train_from_berkeley_image_annotation_pairs + train_from_pascal_image_annotation_pairs
TypeError: unsupported operand type(s) for +: 'zip' and 'zip'

How to resolve this issue?
Thanks a lot!

**Comment by niuliang42** [comment]
Totally same problem, I think this is probably due to the laziness of Py3k. Just try to change all `zip(...)` to `list(zip(...))` in "src/tf-image-segmentation/tf_image_segmentation/utils/pascal_voc.py".
 I fixed it by doing that, hopefully it will work for you as well.

**Comment by wukaoliu** [comment]
Thanks for your ansswer. But I tried the method you said. It is still the same bug as usual. 
  File "/home/ppg/src/tf-image-segmentation/tf_image_segmentation/utils/pascal_voc.py", line 570, in get_augmented_pascal_image_annotation_filename_pairs
    train_from_berkeley_image_annotation_pairs + train_from_pascal_image_annotation_pairs
TypeError: unsupported operand type(s) for +: 'zip' and 'zip'

**Comment by wukaoliu** [comment]
Traceback (most recent calls WITHOUT Sacred internals):
  File "data_pascal_voc.py", line 205, in pascal_voc_setup
    combined_annotations_path)
  File "data_pascal_voc.py", line 139, in pascal_voc_berkeley_combined
    overall_val_image_annotation_filename_pairs,
TypeError: can only concatenate list (not "zip") to list

**Comment by zhaoxuyan** [comment]
@wangxiaodiu  非常感谢！已解决

**Comment by YANRUI121** [comment]
I had the same problem, and when I added the following function definition which is from **keras.preprocessing.image.ImageDataGenerator**, the error was fixed.


`def transform_matrix_offset_center(matrix, x, y):
    o_x = float(x) / 2 + 0.5
    o_y = float(y) / 2 + 0.5
    offset_matrix = np.array([[1, 0, o_x], [0, 1, o_y], [0, 0, 1]])
    reset_matrix = np.array([[1, 0, -o_x], [0, 1, -o_y], [0, 0, 1]])
    transform_matrix = np.dot(np.dot(offset_matrix, matrix), reset_matrix)
    return transform_matrix`


Traceback (most recent call last):
  File "train.py", line 237, in <module>
    label_suffix=label_suffix, ignore_label=ignore_label, label_cval=label_cval)
  File "train.py", line 169, in train
    class_weight=class_weight
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/home/yanrui/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/yanrui/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/yanrui/anaconda3/lib/python3.7/site-packages/keras_preprocessing/image/iterator.py", line 65, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/yanrui/src/Keras-FCN/utils/SegDataGenerator.py", line 260, in _get_batches_of_transformed_samples
    x, y = self.seg_data_generator.random_transform(x, y)
  File "/home/yanrui/src/Keras-FCN/utils/SegDataGenerator.py", line 461, in random_transform
    transform_matrix = transform_matrix_offset_center(
NameError: name 'transform_matrix_offset_center' is not defined
